name: Build
on:
 push:
   branches:
     - main
     - develop
     - feat/*
     - fix/*
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'
      - uses: browser-actions/setup-chromium@v1
      - run: yarn install --frozen-lockfile
        name: Fetch Dependencies
      - run: yarn test:unit:coverage
        name: Run Unit Tests (Vitest)
      - run: yarn coverage:e2e
        name: Run Cypress Tests with Coverage

      - name: Merge coverage (unit + e2e) into coverage/lcov.info
        if: always()
        run: |
          # Ensure unit and e2e LCOV exist
          test -f coverage-unit/lcov.info || echo "warning: missing unit lcov"
          test -f coverage-e2e/lcov.info || echo "warning: missing e2e lcov"
          # Merge via project script to avoid empty LCOVs
          yarn coverage:merge

      - name: Coverage summary (text)
        if: always()
        run: |
          echo "Unit LCOV: $(test -f coverage-unit/lcov.info && wc -l < coverage-unit/lcov.info || echo 0) lines"
          echo "E2E  LCOV: $(test -f coverage-e2e/lcov.info && wc -l < coverage-e2e/lcov.info || echo 0) lines"
          echo "Merged LCOV: $(test -f coverage/lcov.info && wc -l < coverage/lcov.info || echo 0) lines"

      - name: Remove HTML coverage directories (avoid invalid artifact paths)
        if: always()
        run: |
          rm -rf coverage/lcov-report || true
          rm -rf coverage-unit/lcov-report || true
          rm -rf coverage-e2e/lcov-report || true

      - name: Upload coverage reports (LCOV only)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage/lcov.info
            coverage-unit/lcov.info
            coverage-e2e/lcov.info
          if-no-files-found: ignore

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >-
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info