name: Build
on:
 push:
   branches:
     - main
     - develop
     - feat/*
     - fix/*
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'
      - uses: browser-actions/setup-chromium@v1
      - run: npm install --frozen-lockfile
        name: Fetch Dependencies
      - run: npm run dev &
        name: Start Application
      - run: npx cypress run --headless --browser chrome
        name: Run Cypress Tests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}